options:
  merge-default-rules: false
  formatter: html
  output-file: 'coverage/sass-lint.html'
  max-warnings: 50
files:
  include: "src/**/*.s+(a|c)ss"
  ignore:
    - 'node_modules/**/*.scss'
syntax:
  include:
    - scss
    - sass
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 4
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
#  variable-for-property:
#    - 2
#    -
#      properties:
#        - color
#        - background
#        - border